### ISSUE TITLE
Config is not a class (TypeError)

### ISSUE THREAD

**Issue by mvidner** [VPSMatrix/vpsx-ruby#1]
Hi!

I wanted to try out vpsmatrix, but it does not work on Ruby 2.1:

```sh
$ vpsx -h
/local/home-mvidner/.gem/ruby/2.1.0/gems/vpsmatrix-0.1.8/lib/vpsmatrix/config.rb:3:in `<top (required)>': Use RbConfig instead of obsolete and deprecated Config.
/local/home-mvidner/.gem/ruby/2.1.0/gems/vpsmatrix-0.1.8/lib/vpsmatrix/config.rb:3:in `<top (required)>': Config is not a class (TypeError)
...
$ irb
irb(main):001:0> Config
(irb):1:in `irb_binding': Use RbConfig instead of obsolete and deprecated Config.
=> RbConfig::Obsolete
irb(main):002:0> Config.class
=> Module
irb(main):003:0> RUBY_DESCRIPTION
=> "ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux-gnu]"
```

With Ruby 2.4 it does not get better:
```sh
$ irb
irb(main):001:0> RUBY_DESCRIPTION
=> "ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]"
irb(main):002:0> Config
NameError: uninitialized constant Config
Did you mean?  RbConfig
```

**Comment by mariancelo** [comment]
new version 0.1.9 is available

- class Config was renamed to Conf for 2.0 ruby compatibility
- help is now available via -h option
